### ISSUE TITLE
test/proton/Makefile fails with "ERROR 404: Not Found"

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-amqp1.0#19]
The rabbitmq-amqp1.0/test/proton/Makefile fails with "ERROR 404: Not Found". It tries to download the proton 0.7 client from a mirror that stores newer versions only.

```
PROTON_VER=0.7
PROTON_URL=http://www.mirrorservice.org/sites/ftp.apache.org/qpid/proton/$(PROTON_VER)/$(PROTON_TARBALL)
```

However, the mirrorservice.org does not store v0.7 anymore. It stores 0.9, 0.9.1 and 0.10 only.

**Comment by kjnilsson** [comment]
There is no longer a Makefile. Both java and dotnet tests are run through common_test so closing this.
