### ISSUE TITLE
Make AMQP 1.0 plugin production worthy

### ISSUE THREAD

**Issue by 4integration** [rabbitmq/rabbitmq-amqp1.0#58]
Hi,

I am working at a large enterprise where we have architectural principles like conformity to standards & build flexible solutions.
Since AMQP 1.0 is OASIS standardized and nowadays widely supported by many client API's and message brokers I really thinks it is a pity that RabbitMQ only have this as "experimental" plugin. It should be seen as first class citizen in the RabbitMQ product.

Since it is "experimental" there are issues convincing management to use it in business critical solutions and not using it (instead using AMQP 0.9.1) introduces other issues like loosing flexibility (mixing RabbitMQ on-premise and Azure SB in the cloud). 

I would strongly vote for making AMQP 1.0 plugin **more complete** by implementing support for the current major limitations like transactions and publish it as **production ready**. 
Otherwise I think RabbitMQ will loose "market share" where competitors gain by support AMQP 1.0 (like Azure Service Bus, IBM MQ, Apache ActiveMQ and Apache Qpid)

**Comment by michaelklishin** [comment]
Discussions belong to the mailing list.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/I0CPk9kbwcM).
