### ISSUE TITLE
Publishing to a queue pre-declared with arguments fails

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-amqp1.0#7]
When I declare a queue with some arguments (e.g. x-max-length, or x-expires) and then try to publish to this queue via AMQP 1.0's amqp://localhost/queue, the publish fails and broker reports "PRECONDITION_FAILED - inequivalent arg".
This is because the AMQP 1.0 plug-in tries to declare the queue before publishing the message and declares it without any argument. Since the queue is already declared without any argument, the operation fails.
Should the amqp 1.0 plugin really declare the queue before publishing a message, it should ignore the error #406 because the queue might have been declared with other arguments.

**Comment by gotthardp** [comment]
Some queue parameters (for now, durability only) are dynamically decided upon the requested endpoint parameters. It actually *does* make sense to report PRECONDITION_FAILED when there is a mismatch between the queue durability and the requested endpoint durability.
A better solution might be to allow users to define custom arguments (e.g. x-max-length) for the queues ensured by AMQP1.0.

**Comment by kjnilsson** [comment]
Right. I think we should discuss making use of the link target's `dynamic` flag that indicates that the target node should be dynamically created. Currently we [do not support](https://github.com/rabbitmq/rabbitmq-amqp1.0/blob/b9b6154b290f8ba4bee9d8534488eab67b4ae4b1/src/rabbit_amqp1_0_incoming_link.erl#L200-L206) `dynamic` but still _create the target_ (!), i.e. a queue, exchange etc in what I consider a dynamic fashion. 
The reason for this may be that when `dynamic` is set on a target the address field has to be unset. I think there is an alternative.

I propose we change the plugin such that nodes (queues/exchanges) are only created when the `dynamic` flag is set on the target. Properties such as name and type of the node can be communicated using the `dynamic-node-properties` field (a `map`). If `dynamic` is not set the plugin won't attempt to create the queue during link setup. We may want to introduce a step that checks if the queue exists at all. I will have to check what semantics are normally expected in this case. 

This is quite a substantial breaking change. WDYT? @michaelklishin @dumbbell @gerhard @dcorbacho @acogoluegnes @hairyhum @khhuff

**Comment by kjnilsson** [comment]
here is an excerpt from the spec (2.6.3) that is relevant:

_The application attempts to locate the Terminus previously associated with the Link. This Terminus is associated with the Link Endpoint and may be updated if its properties do not match those sent by the remote Link Endpoint. If no such Terminus exists, the application MAY choose to create one using the properties supplied by the remote Link Endpoint. The Link Endpoint is then mapped to an unused handle, and an attach Frame is issued carrying the state of the newly created endpoint. Note that if the application chooses not to create a Terminus, the Session Endpoint will still create a Link Endpoint and issue an attach indicating that the Link Endpoint has no associated local terminus. In this case, the Session Endpoint MUST immediately detach the newly created Link Endpoint._

**Comment by kjnilsson** [comment]
and here is the section on the creation of dynamic nodes (3.5.4)

*dynamic* request dynamic creation of a remote Node
When set to true by the sending Link endpoint, this field constitutes a request for the receiving peer to dynamically create a Node at the target. In this case the address field MUST NOT be set.
When set to true by the receiving Link Endpoint this field indicates creation of a dynamically created Node. In this case the address field will contain the address of the created Node. The generated address SHOULD include the Link name and Session-name or client-id in some recognizable form for ease of traceability.

*dynamic-node-properties* properties of the dynamically created Node
If the dynamic field is not set to true this field must be left unset.
When set by the sending Link endpoint, this field contains the desired properties of the Node the sender wishes to be created. When set by the receiving Link end- point this field contains the actual properties of the dynamically created node. See subsection 3.5.9 Node Properties._

**Comment by michaelklishin** [comment]
Sounds good (and similar to what we do in STOMP).

**Comment by gerhard** [comment]
The proposed changes make sense, I am wondering about the naming `dynamic-node-properties` field naming. Would `dynamic-properties` make more sense? Then we can capture the type of the node (queue or exchange) in the map `dynamic-properties` map itself.

**Comment by kjnilsson** [comment]
@gerhard `dynamic-node-properties` is part of the amqp 1.0 spec so we can't change the naming there. As you say it would make sense to communicate type and name in this map. We could also optionally support all the queue / exchange properties that rabbit currently support in there.

**Comment by kjnilsson** [comment]
An additional thought. With this we could support the creation of server generated queue names when the `name` property is omitted for a queue `type`.

**Comment by kjnilsson** [comment]
Ok so it turns out that when addressing queues created outside of the amqp1.0 context one should use the `/amq/queue/<queue_name>` address format just like for the stomp adaptor. This won't try to declare the queue.  /cc @gotthardp 

I still think we should consider implementing `dynamic` to provide an option to allow more control over the queue properties but as far as this issue goes it should be considered resolved. I will raise a separate ticket for `dynamic`.
