### ISSUE TITLE
Consider dropping supervisor2

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-amqp1.0#96]
`supervisor2` hasn't been updated to support map flags and child specs. While this can be corrected, we should reconsider its use. It seems to be used only in a few places and replacing it with the standard `supervisor` might be quite straightforward.

**Comment by kjnilsson** [comment]
As the supervisor2s use the `intrinsic` restart type I'm not sure there is an equivalent using a vanilla `supervisor`

https://github.com/rabbitmq/rabbitmq-amqp1.0/blob/164e5dfab8e5a767542a63a80664dccdeb13388a/src/rabbit_amqp1_0_session_sup.erl#L39

**Comment by michaelklishin** [comment]
The question is, do we need this restart type in most places. I bet we don't.

**Comment by lukebakken** [comment]
We still :heart: `supervisor2` https://github.com/rabbitmq/rabbitmq-common/pull/411
